# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-23 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(max_length=4)),
                ('term', models.PositiveSmallIntegerField(max_length=1)),
                ('grade', models.PositiveSmallIntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(max_length=3)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('average', models.FloatField()),
                ('zscore', models.FloatField()),
                ('attendence', models.FloatField()),
                ('rank', models.PositiveSmallIntegerField(max_length=3)),
                ('classRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.ClassRoom')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('index', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.Student'),
        ),
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.Student'),
        ),
        migrations.AddField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.Subject'),
        ),
    ]
