# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-23 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='term',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='rank',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
