# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-24 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0002_auto_20170423_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.FloatField(),
        ),
    ]
