# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-26 12:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0004_rowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowner',
            name='date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2017, 4, 26, 12, 45, 47, 490923, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
