# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-26 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0005_rowner_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
