# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-28 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0008_message_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mr_mrs',
            field=models.CharField(max_length=3),
        ),
    ]
