# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0009_auto_20170428_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='mr_mrs',
        ),
    ]
